server:
  port: 8081

spring:
  data:
    mongodb:
      database: panteaoCronusDB
      host: localhost
      port: 27017

#logging:
#  level:
#    org:
#      springframework:
#        data:
#          mongodb:
#            core:
#              MongoTemplate: DEBUG