server:
  port: 8081

spring:
#  datasource:
#    driver-class-name: mongodb.jdbc.MongoDriver
  data:
    mongodb:
      database: panteaoCronusDB
      host: localhost
      port: 27017
#  jpa:
#    hibernate:
#      ddl-auto: create
  jpa:
    show-sql: true
hibernate.show_sql: true
#  autoconfigure:
#    exclude:
#      org:
#        springframework:
#          boot:
#            autoconfigure:
#              jdbc: DataSourceAutoConfiguration
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG